<?php
/**
 * CategoryTreeApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  eBay\Commerce\Taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Taxonomy API
 *
 * Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace eBay\Commerce\Taxonomy\Test\Api;

use \eBay\Commerce\Taxonomy\Configuration;
use \eBay\Commerce\Taxonomy\ApiException;
use \eBay\Commerce\Taxonomy\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CategoryTreeApiTest Class Doc Comment
 *
 * @category Class
 * @package  eBay\Commerce\Taxonomy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CategoryTreeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fetchItemAspects
     *
     * Get Aspects for All Leaf Categories in a Marketplace.
     *
     */
    public function testFetchItemAspects()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategorySubtree
     *
     * Get a Category Subtree.
     *
     */
    public function testGetCategorySubtree()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategorySuggestions
     *
     * Get Suggested Categories.
     *
     */
    public function testGetCategorySuggestions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCategoryTree
     *
     * Get a Category Tree.
     *
     */
    public function testGetCategoryTree()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompatibilityProperties
     *
     * Get Compatibility Properties.
     *
     */
    public function testGetCompatibilityProperties()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompatibilityPropertyValues
     *
     * Get Compatibility Property Values.
     *
     */
    public function testGetCompatibilityPropertyValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDefaultCategoryTreeId
     *
     * Get a Default Category Tree ID.
     *
     */
    public function testGetDefaultCategoryTreeId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getItemAspectsForCategory
     *
     * .
     *
     */
    public function testGetItemAspectsForCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
